/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#231f14",
        "primary": "#fff6df",
        "tertiary-fixed": "#e3e2e0",
        "on-surface-variant": "#d0c6ab",
        "secondary-fixed": "#e5e2e1",
        "outline-variant": "#4d4732",
        "on-primary-container": "#705e00",
        "on-secondary-fixed-variant": "#474746",
        "on-error": "#690005",
        "surface-variant": "#393528",
        "surface-tint": "#e9c400",
        "error-container": "#93000a",
        "surface-container-lowest": "#110e05",
        "primary-fixed": "#ffe16d",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#393528",
        "primary-container": "#ffd700",
        "tertiary": "#f7f6f4",
        "surface": "#161308",
        "on-primary": "#3a3000",
        "on-tertiary-container": "#5f5f5e",
        "surface-container-low": "#1f1b10",
        "on-tertiary-fixed-variant": "#464746",
        "inverse-primary": "#705d00",
        "error": "#ffb4ab",
        "on-tertiary": "#303130",
        "on-secondary": "#313030",
        "on-background": "#eae2cf",
        "primary-fixed-dim": "#e9c400",
        "surface-bright": "#3d392c",
        "secondary-container": "#474746",
        "on-tertiary-fixed": "#1b1c1b",
        "on-primary-fixed-variant": "#544600",
        "on-primary-fixed": "#221b00",
        "tertiary-container": "#dbdad8",
        "secondary": "#c8c6c5",
        "on-secondary-container": "#b7b5b4",
        "inverse-on-surface": "#343024",
        "background": "#161308",
        "on-surface": "#eae2cf",
        "inverse-surface": "#eae2cf",
        "secondary-fixed-dim": "#c8c6c5",
        "outline": "#999077",
        "surface-dim": "#161308",
        "tertiary-fixed-dim": "#c7c6c4",
        "surface-container-high": "#2e2a1e",
        "on-secondary-fixed": "#1c1b1b"
      },
      spacing: {
        "unit": "4px",
        "gutter": "24px",
        "container-max-width": "1440px",
        "margin-mobile": "16px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "stat-value": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-hero": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["48px", { "lineHeight": "56px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "stat-value": ["32px", { "lineHeight": "32px", "fontWeight": "800" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-hero": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "900" }]
      }
    }
  },
  plugins: [],
}
